### ISSUE TITLE
Nullstill brett funker ikke

### ISSUE THREAD

**Issue by CaptainKims** [sosialkontoret/fredagsbingo#3]
Når du klikker på "nullstill brett", kan du velge "Ja" eller "Nei". Ingen av disse har en funksjon. I tillegg får du en ny prompt i tillegg for hver gang du trykker på "Nullstill brett".

**Comment by boyum** [comment]
Takk for at du sier fra!! I hvilken nettleser ser du dette?

**Comment by CaptainKims** [comment]
Safari 13.1.2 på Catalina
